apiVersion: v2
name: monitoring
description: Monitoring stack for student management system
type: application
version: 0.1.0

dependencies:
  - name: kube-prometheus-stack
    version: "56.6.0"
    repository: "https://prometheus-community.github.io/helm-charts"