apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: karpenter
  namespace: argocd

spec:
  project: default

  source:
    repoURL: https://github.com/ashubambal/student-management-k8s.git
    targetRevision: main
    path: charts/karpenter

  destination:
    server: https://kubernetes.default.svc
    namespace: karpenter

  syncPolicy:
    automated:
      prune: true
      selfHeal: true