apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: student-management
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/ashubambal/student-management-k8s.git
    chart: student-management
    targetRevision: main
    helm:
      valueFiles:
        - values.yaml

  destination:
    server: https://kubernetes.default.svc
    namespace: default

  syncPolicy:
    automated:
      prune: true
      selfHeal: true