apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-init-script

data:
  init.sql: |
    CREATE DATABASE IF NOT EXISTS studentsdb;

    USE studentsdb;

    CREATE TABLE IF NOT EXISTS students (
        id INT AUTO_INCREMENT PRIMARY KEY,
        name VARCHAR(100),
        age INT,
        branch VARCHAR(100),
        year INT,
        email VARCHAR(150),
        password VARCHAR(100),
        photo VARCHAR(200)
    );