apiVersion: v2
name: namespaces
description: Namespaces for Student Management System
type: application
version: 0.1.0
appVersion: "1.0"
maintainers:
  - name: Ashutosh Bambal
    email: ashutoshbambal@gmail.com