frontend:
  image: softconsist/student-frontend
  tag: latest
  replicas: 2
  servicePort: 80

backend:
  image: softconsist/student-backend
  tag: prod-v16
  replicas: 2
  servicePort: 3000

mysql:
  image: mysql
  tag: 8
  rootPassword: password
  database: studentsdb